##
##  Makefile -- Build procedure for sample test Apache module
##  Autogenerated via ``apxs -n test -g''.
##

builddir=build
top_srcdir=/opt/local/apache2/
top_builddir=/opt/local/apache2/

include /opt/local/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=/opt/local/apache2/bin/apachectl

CFLAGS=-g

#   additional defines, includes and libraries

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_zlibdict.o mod_zlibdict.lo mod_zlibdict.slo mod_zlibdict.la

#   simple test
test: reload
	lynx -mime_header http://localhost/test

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

