##
##  Makefile -- Build procedure for sample test Apache module
##  Autogenerated via ``apxs -n test -g''.
##

builddir=build
#top_srcdir=/usr
top_builddir=/opt/local/apache2/
include /opt/local/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f build/mod_zlibdict.o build/mod_zlibdict.lo build/mod_zlibdict.slo build/lsmod_zlibdict.la

#   simple test
test: reload
	lynx -mime_header http://localhost/test

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

